### PR TITLE
Observers

### PR DESCRIPTION
**Pull request by hsd-dev**
The package now supports 3 observers: `ROSGraphObserver` (base class `ServiceObserver`), `QualityObserver` (base class `TopicObserver`) (example), `LogObserver`[WIP].

Below is an example implementation of a `TopicObserver` (function `perform_check` should be implemented by each subclass of `TopicObserver`). 
https://github.com/ipa-hsd/rosgraph_monitor/blob/6e986bfce4916773b0b7a0d1365fdcfeee1561f0/src/rosgraph_monitor/observers/quality_observer.py#L5-L23

Additionally, the package exposes following services:
- `/load_observer "name: 'Dummy'"`
- `/unload_observer "name: 'Dummy'"`
- `/list_observers "{}"`
- `/active_observers "{}"`

### CODE REVIEW

**Comment by hsd-dev** [comment]
@ipa-nhg @chcorbato

**Comment by chcorbato** [comment]
Nice!
For the `QualityObserver` I was assuming it would publish a `diagnostic_array.msg` with the following semantics (for example for an observer reporting the Quality attribute energy):
```
level = 1
name = objective.id (this value is passed to the QualityObserver upon initialization)
message = "QA status"
values = [{"energy", "3.5"}]
```
That is, the `QualityObserver` basically reports the value for the Quality Attribute "energy", and it is up to the metacontrol reasoning to decide whether that value is acceptable or not.

What do you think @ipa-hsd @ipa-nhg ?

**Comment by hsd-dev** [comment]
@chcorbato publishing the `diagnostic_array.msg` was taken care by `QualityObserver`'s base class `TopicObserver`:
https://github.com/ipa-hsd/rosgraph_monitor/blob/6e986bfce4916773b0b7a0d1365fdcfeee1561f0/src/rosgraph_monitor/observer.py#L108-L117

I will modify it according to your comment.

**Comment by hsd-dev** [comment]
Probably something like this:
https://github.com/ipa-hsd/rosgraph_monitor/blob/817c460fbc09462e01d9ced4a2e072c69300a662/src/rosgraph_monitor/observers/quality_observer.py#L6-L32

**Comment by NadiaHG** [comment]
Great job @ipa-hsd! I really like the design of the code and the use of services to list, load and unload observers! Thanks for this contribution! :tada: 

I know that this implementation is the most convenient one to cover the current needs to connect a ROS running system with the metacontrol, but from my point of view and thinking on future improvements, the general concept of an observer is a bit confuse here:
- the sentence "subscribe to several topics, combine the information of them and publish the result" can probably describe the majority of the existing ROS drivers and make not sense to call them observers. I think the logic shouldn't be part of the observer, publish the correct information should be the work of the driver of the component or the developer/integrator should implement a separate node to do this and publish the resulted information as a proper ROS msg (also to don't loose the nature of the data, is it a Int?, a String?...?)
- publish the result of the operation as a diagnostic status message. On one hand, unify to a single message type all the information and you get the data from all the observers combined as an array of messages, but on the other hand, for this case you are not diagnosing things (actually the diagnostics level is always OK) you have just a relay of data, this is not consistent with the description of a DiagnosticStatus message.

From the technical point of view, if you force the developer (the code auto-generator) to add to this ROS package all the observer nodes, you have to consider that for each new observer node the package.xml of the package have to be updated to include as dependency the ROS package that holds the messages definition. Thinking out loud, is this something maintainable?

**Comment by hsd-dev** [comment]
Valid points @ipa-nhg! I have some ideas on how to go ahead. Let's take it up on a new thread. Thanks @chcorbato and @ipa-nhg for your feedbacks! I will merge this for now.

**Comment by chcorbato** [comment]
> Great job @ipa-hsd! I really like the design of the code and the use of services to list, load and unload observers! Thanks for this contribution! 🎉

Great job indeed! 

> I know that this implementation is the most convenient one to cover the current needs to connect a ROS running system with the metacontrol, but from my point of view and thinking on future improvements, the general concept of an observer is a bit confuse here:
> 
> * the sentence "subscribe to several topics, combine the information of them and publish the result" can probably describe the majority of the existing ROS drivers and make not sense to call them observers. I think the logic shouldn't be part of the observer, publish the correct information should be the work of the driver of the component or the developer/integrator should implement a separate node to do this and publish the resulted information as a proper ROS msg (also to don't loose the nature of the data, is it a Int?, a String?...?)

In my view, a `metacontrol Observer` has a different role than a `driver`:
- the purpose of a `driver`'s role is to abstract the capability provided by a piece of hardware to use it in any computing-based/information application. So they are application-independent
- the purpose of a `metacontrol Observer` is to transform existing dataflows in the system into **application-specific** information about the quality of the performance of the system

> * publish the result of the operation as a diagnostic status message. On one hand, unify to a single message type all the information and you get the data from all the observers combined as an array of messages, but on the other hand, for this case you are not diagnosing things (actually the diagnostics level is always OK) you have just a relay of data, this is not consistent with the description of a DiagnosticStatus message.

I agree that probably for the observers we need different semantics than for diagnostics, because of the different purpose of the information they provide.
But for the moment we agreed to reuse `DiagnosticStatus.msg` for simplicity, so as not to create yet another ad-hoc type.
> 
> From the technical point of view, if you force the developer (the code auto-generator) to add to this ROS package all the observer nodes, you have to consider that for each new observer node the package.xml of the package have to be updated to include as dependency the ROS package that holds the messages definition. Thinking out loud, is this something maintainable?

> (@ipa-hsd) Let's take it up on a new thread.

Let us know where do you want to open that thread! I'll be happy to contribute if you are interested.

**Pull request merged**
