### PR TITLE
Param check

### PR DESCRIPTION
**Pull request by hsd-dev**
The result is for COB4 simulation. For visual purpose, not showing the "Additional Nodes" and "Missing Nodes" below.
```
level: 2
name: "parameters_node"
message: "Wrong param configuration"
hardware_id: ''
values: 
  - 
    key: "battery_monitor/enable_light"
    value: "false"
  - 
    key: "collision_velocity_filter/anti_collision_costmap/resolution"
    value: "0.05"
  - 
    key: "diagnostic_aggregator/analyzers/computers/analyzers/b1/contains"
    value: "['b1 CPU Info', 'b1 CPU Usage', 'b1 HD Usage', 'b1 Memory Usage']"
  - 
    key: "light_base/sim_enabled"
    value: "true"
  - 
    key: "joint_state_publisher/source_list"
    value: "['/base/joint_states']"
  - 
    key: "emergency_stop_monitor/enable_sound"
    value: "false"
  - 
    key: "collision_velocity_filter/anti_collision_costmap/plugins"
    value: "[[['type', 'costmap_2d::ObstacleLayer']], [['name', 'obstacle_layer_0']]]"
  - 
    key: "use_sim_time"
    value: "true"
  - 
    key: "robot_description"
    value: "..."
  - 
    key: "collision_velocity_filter/anti_collision_costmap/global_frame"
    value: "base_footprint"

```

### CODE REVIEW

**Comment by hsd-dev** [comment]
@ipa-nhg @chcorbato: not sure if you wanted to club all wrong parameters in a node in a single `DiagnosticStatus` message

**Comment by NadiaHG** [comment]
@ipa-hsd  Great job, thanks a lot :tada: 

In case we use minimal "desired"_model as input, it should be ok if we club all the wrong parameters within a single Diagnostics message, probably the desired system will only ask for the analysis of a single node/component.

-----

However, is it too complex to implement this software to support different configurations? For example using a parameter that set different analysis modes, i.e:

- critical: all the errors including warnings because of additional nodes/parameters..
- minimal: missed nodes and parameters and check values 
- minimal_verbose: missed nodes and parameters and check values, single diagnostic status per wrong parameter

If this is super complex or this is useless for your use cases, just ignore this comment!

**Comment by chcorbato** [comment]
> @ipa-nhg @chcorbato: not sure if you wanted to club all wrong parameters in a node in a single `DiagnosticStatus` message

clubbing all the params for a node in a message is perfectly ok with me.

**Comment by hsd-dev** [comment]
@ipa-nhg said:
> However, is it too complex to implement this software to support different configurations? For example using a parameter that set different analysis modes

I will handle this in a new PR. I will merge this PR.

**Pull request merged**
